### PR TITLE
Migrate to Webpack v5

### PR DESCRIPTION
**Pull request by mwiencek**
https://webpack.js.org/blog/2020-10-10-webpack-5-release/

Lots of plugins are dropping support for Webpack v4, so we have to perform this upgrade eventually (it's close to a year old now).  There are some new features I'd like to use, too.

I've enabled the new [persistent caching](https://github.com/webpack/changelog-v5/blob/master/guides/persistent-caching.md) feature; see webpack/cacheConfig.js.

Tested by compiling resources, running tests, and browsing the site for errors.

### CODE REVIEW

**Review by reosarevok — APPROVED** [review]
Some quick testing locally seems to show no issues, although of course I didn't touch every page. This seems like the kind of thing that would benefit from being put in beta to find potential bugs.

**Comment by reosarevok** [comment]
Actually, I did notice one issue: the Type: reltype bits of the new url editor have a working style on master:

```
#external-links-editor .relationship-item div.relationship-content label {
    margin-right: 6px;
    white-space: nowrap;
}
```

But they seem to have a borked one on your branch: 

```
#external-links-editor .relationship-item div.relationship-content label {
    ⚠️ margin-right: 12px / 2;
    white-space: nowrap;
}
```

**Review by reosarevok — CHANGES_REQUESTED** [review]
Actually, I did notice one issue: the Type: reltype bits of the new url editor have a working style on master:

```
#external-links-editor .relationship-item div.relationship-content label {
    margin-right: 6px;
    white-space: nowrap;
}
```

But they seem to have a borked one on your branch: 

```
#external-links-editor .relationship-item div.relationship-content label {
    ⚠️ margin-right: 12px / 2;
    white-space: nowrap;
}
```

An issue with the change in the way we use less files?

**Comment by mwiencek** [comment]
Good catch -- they made it so that divisions have to be inside parentheses now, I guess due to some parser ambiguity.  Fixed now.  I did a search for other cases and fixed all the ones I found.

**Review by reosarevok — APPROVED** [review]
Thanks! As such, I'm back to my original opinion:

> Some quick testing locally seems to show no issues, although of course I didn't touch every page. This seems like the kind of thing that would benefit from being put in beta to find potential bugs.

**Pull request merged**
