### PR TITLE
Grammatical errors removed.

### PR DESCRIPTION
**Pull request by rakshitkumarcse**
I have removed several grammatical errors.

### CODE REVIEW

**Comment by yvanzo** [comment]
@brainzbot test this please.

**Comment by rakshitkumarcse** [comment]
Kindly merge the request.

**Comment by rakshitkumarcse** [comment]
@yvanzo I have recently started contributing to metabrainz. I am a sophomore and an undergraduate pursuing computer science. I am aiming for gsoc as well. Can you guide me how should I start getting familiar with metabrainz and

**Comment by yvanzo** [comment]
@rakshitkumarcse Great, see [our introduction to GSoC](https://musicbrainz.org/doc/Development/Summer_of_Code/Getting_started). Note that MetaBrainz is the organization, whereas MusicBrainz is one of [its projects](https://metabrainz.org/projects), historically the main one. We are currently [converting templates to React.js](https://tickets.metabrainz.org/browse/MBS-8609), you might want to participate, take a look at [closed pull requests](https://github.com/metabrainz/musicbrainz-server/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+%22to+React%22) to see what it looks like. Otherwise, you might be interested into implementing [search field for "any" entity type](https://tickets.metabrainz.org/browse/MBS-9756) which relies on already converted templates. [Smaller bugs](https://tickets.metabrainz.org/issues/?jql=project%3DMBS%20AND%20status%3DOpen%20AND%20%22Size%20Estimate%22%20%3D%20House) are open too, as well as [other projects](https://tickets.metabrainz.org/secure/BrowseProjects.jspa?selectedCategory=all&selectedProjectType=all). See you soon on IRC!

**Comment by rakshitkumarcse** [comment]
@yvanzo Thanks a lot for the great help. Your comment clarified all my doubts and has given me a great insight into the current affairs of the repo. I hope I can contribute as much as possible.
Looking forward to contributing and receiving such great guidance from you.

**Pull request merged**
