### PR TITLE
MBS-9488: Changing "Limited editor" to "Beginner"

### PR DESCRIPTION
**Pull request by reosarevok**
https://tickets.metabrainz.org/browse/MBS-9488 - I think I caught it all but I can't test stuff locally because no local DB.

### CODE REVIEW

**Comment by mwiencek** [comment]
After seeing it I may have changed my mind about renaming it in the code, since it's confusing there (new implies only recent to me, and limited is already well understood in the code). Of course I'm fine with changing the user visible text. Sorry. :/ Unless @yvanzo disagrees.

**Comment by reosarevok** [comment]
Changed this to only make visual changes.

**Comment by yvanzo** [comment]
Actually “new implies only recent to me” too, and probably to many people as well, whereas this status is based on time and editing experience (less than 10 accepted edits). Would “beginner” be a best fit?

**Comment by reosarevok** [comment]
I thought about that but considered that new can be seen in both time and experience (even if I created my account ten years ago, if I haven't edited anything, I'm still a new editor). But I'm ok with both options.

**Comment by yvanzo** [comment]
That would be the same wording as in “[Beginners Guide](https://musicbrainz.org/doc/Beginners_Guide)”.

**Comment by mwiencek** [comment]
I'm ok with either, I like "Beginner" slightly more.

**Comment by reosarevok** [comment]
Changed it to "Beginner"

**Pull request merged**
