### PR TITLE
MBS-8968: Output gender MBIDs in /ws/2 XML

### PR DESCRIPTION
**Pull request by mwiencek**
Already fixed mmd-schema to recognize this.

### CODE REVIEW

**Comment by gentlecat** [comment]
Looks like something is wrong with `t::MusicBrainz::Server::Controller::WS::2::LookupArtist`.

**Comment by mwiencek** [comment]
Ah, I think it's because it's building against an outdated mmd-schema. I'll update that and trigger a new build.

**Comment by mwiencek** [comment]
Jenkins PR thing won't build the right commit, but `prove -vl t/tests.t :: --tests LookupArtist` is passing for me locally.

**Comment by gentlecat** [comment]
:shipit:

**Pull request merged**
