### PR TITLE
MBS-8798: invert paginator colours, make hover text white

### PR DESCRIPTION
**Pull request by reosarevok**
I feel this is more consistent. Also, white on hover makes the number more visible.

### CODE REVIEW

**Comment by mwiencek** [comment]
:shipit:

**Comment by mwiencek** [comment]
Is this more consistent though? The menus are orange on hover so I'd expect other buttons to be orange on hover too. But the menus don't have any concept of "selected" I guess, just hovered.

**Comment by reosarevok** [comment]
Well, it will be for sure if we merge the tabs PR as is :p As it is, my feel was that on hover = open menu = active (BTW, noticed menus are not orange when clicked on mobile, maybe I should look into that too)

**Comment by mwiencek** [comment]
True, orange = active does make sense for the top-level menu headers. But you'd still have tab hover = white bg, purple border, and paginator hover = purple bg, white text. I'd expect purple bg/white text for the tabs, too, and also the menu links. Could be that I'm crazy, so if you think everything's consistent then we can merge it all.

And strange, the menus turned orange for me (when I was testing the clickable menu branch) on ios yesterday.

**Comment by reosarevok** [comment]
Hmm. I thought purple BG, white text might be a bit too colorful for this case (while on the paginators it didn't feel too distracting) but we could try it if you want!

**Comment by mwiencek** [comment]
Merged the tabs PR (you might be right about it being too bold/colorful there).

Using a purple border for the pagination looks pretty good to me, but we'd also need to add spacing between the buttons like the tabs have (so, stop collapsing the borders), otherwise it's hard to get a consistent outline on all four sides:

spaced paginator buttons with purple border on hover

That looks alright to me though, what do you think?

**Comment by reosarevok** [comment]
Ooooh, I really like that.

**Comment by gentlecat** [comment]
Looks good, I agree.

**Pull request merged**
