### PR TITLE
MBS-10143: Allow querying for tags/genres on discid ws requests

### PR DESCRIPTION
**Pull request by reosarevok**
https://tickets.metabrainz.org/browse/MBS-10143

# Action

- [ ] Update https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2#discid

### CODE REVIEW

**Comment by mwiencek** [comment]
This looks good, but can we add/update a corresponding test for the JSON WS in t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupDiscID.pm?

**Comment by reosarevok** [comment]
Sure! Done :)

**Comment by reosarevok** [comment]
Does it actually require any documentation update? The docs say "the 'inc=' arguments supported are identical to a lookup request for a release".

**Comment by yvanzo** [comment]
Oh ok, so the doc is currently wrong about `inc=` arguments supported for `discid` lookup, and this patch makes the web service behaves as expected/already documented?

This is a bit beyond this patch, but why the doc refers to `release` here and where can one find this list of supported arguments?

**Pull request merged**
