### PR TITLE
MBS-13646: Add extracted comments to descriptions

### PR DESCRIPTION
**Pull request by yvanzo**
# MBS-13646

## Problem

It isn’t always obvious to translators what the descriptions are supposed to describe.

## Solution

On the model of instrument description translation source strings, for each description (artist type, relationship type…) to be translated, this patch provides the corresponding name as extracted comment which is visible to translators in Weblate and doesn’t discard the existing translations when modified.

As the output of `msguniq` isn’t ideal, a filter script is added in order to sort and deduplicate the extracted comments.
    
As Weblate is just joining extracted comments with a whitespace, the filter script is joining these with a comma instead for readability.

Reference: https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

## Testing

I’ve added extracted comments to the source string `founded`, through commits 6c4fe059db41c6cd9c92cfc3fac7e0c265bc0a99 and 0100f515db3b933a1a536de25c8486d1f9407a0b pushed directly to the branch `beta`, so as to test their display in Weblate. See the [French translation of `founded`](https://translations.metabrainz.org/translate/musicbrainz/relationship-types/fr/?checksum=f53f6a4e155d4bdb) for example.

I’ve tested it locally by running `./po/update_pot.sh` and comparing files with `git diff -- 'po/*.pot'`

Please test it in your own development setup if it isn’t based on `musicbrainz-docker`.

_Edit: I’ve pushed a second commit updating the POT files for comparison._

### CODE REVIEW

**Review by reosarevok — APPROVED** [review]
This seems great! My only suggestion, if it seems sensible to you, would be to make this happen both ways, with the description being shown as comment for the name, since names (for example for instruments but also for relationships) can also be clarified significantly by having the description available to check.

Edit: I was reminded on chat that we don't split the different relationships with the same name (yet), so this might not work very well at the moment. Merging as-is seems good in that case, maybe with a ticket to do the description thing when we can.

**Comment by yvanzo** [comment]
I’ve just opened the ticket MBS-13662 for this purpose.

**Comment by mwiencek** [comment]
On macOS (which has BSD sed) I get:

```
sed: illegal option -- z
usage: sed script [-Ealnru] [-i extension] [file ...]
	sed [-Ealnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
make: *** [statistics.pot] Error 1
```

I do have `gsed` installed too, and replacing all instances of `sed` with `gsed` in po/format_extracted_comments works perfectly. 👍 Could we perhaps fall back to that if available?

**Comment by yvanzo** [comment]
@mwiencek Does the change in commit https://github.com/metabrainz/musicbrainz-server/pull/3300/commits/9cd29fb3c2b15e44d2e09389549d1e9957e7217b work better for you?

**Comment by mwiencek** [comment]
The script no longer crashes, though it logs thousands of lines like:

```
sed: 1: ":line;N;$!b line;s_\n#\ ...": unused label 'line;N;$!b line;s_\n#\._,_g'
sed: 1: ":line;N;$!b line;s_\n#\ ...": unused label 'line;N;$!b line;s_\n#\._,_g'
sed: 1: ":line;N;$!b line;s_\n#\ ...": unused label 'line;N;$!b line;s_\n#\._,_g'
```

**Comment by yvanzo** [comment]
Thank you, let’s require `gsed` then.

**Comment by yvanzo** [comment]
@mwiencek please test with https://github.com/metabrainz/musicbrainz-server/pull/3300/commits/3253619c53213aa3a1c44160e758070138ff3670 instead (snippets copied from docker server configs).

**Comment by yvanzo** [comment]
I just removed the temporary/test commits and explained the macOS compatibility snippet in commit message.

**Pull request merged**
