### PR TITLE
Added output_success() to the JSON serializer.

### PR DESCRIPTION
**Pull request by Zastai**
Makes Accept: application/json work for submissions.

### CODE REVIEW

**Comment by uklauer** [comment]
Can you explain what this does? What submissions? What happened before?

**Comment by Zastai** [comment]
It's the method called by the web service processing for a succesful submission (isrcs, barcodes, etc). Since you post xml for those, it's reasonable to also have the Accept header set to application/xml; but if it's set to application/json, the web service tries to call this method and fails. Adding it is trivial and does no harm, plus it would allow my client library to prefer json all the way.

**Comment by uklauer** [comment]
OK; a bit strange to post XML and receive JSON, but fine with me.

Regarding the rationale: This is exactly what should be in a commit message. Please put it there.

**Comment by Zastai** [comment]
Updated the commit message.

**Pull request merged**
