### PR TITLE
MBS-11919: Remove numeric labels from URLs on new editor

### PR DESCRIPTION
**Pull request by y-young**
# Problem
- MBS-11919: Remove numeric labels from URLs on new editor

# Solution
- Remove link index numbers for simplicity, add a link in duplicate notice to jump to the referenced link. (MBS-11919)

image

### CODE REVIEW

**Comment by y-young** [comment]
@brainzbot Retest this please.

**Comment by y-young** [comment]
@brainzbot Retest this please.

**Comment by reosarevok** [comment]
One thing to keep in mind: if the duplicate link added is a valid autoselectable link (so, there's no need to select a type) then when trying to click the link it will automatically merge it anyway since the field lost focus. That seems a bit confusing, we should probably either show a slightly different error there, or make it so that it's not saved/merged on clicking the link.

**Comment by y-young** [comment]
> One thing to keep in mind: if the duplicate link added is a valid autoselectable link (so, there's no need to select a type) then when trying to click the link it will automatically merge it anyway since the field lost focus.

I guess it'll trigger a "This relationship already exists" error? In that case we should probably block the merge.

**Comment by reosarevok** [comment]
Yeah, it will. It might make sense to block any merge that will trigger that, if that's easy enough to do :)

**Comment by y-young** [comment]
That's an existing issue and it seems not easy to fix, so maybe later in another PR.

**Review by yvanzo — CHANGES_REQUESTED** [review]
This change is twofold, it is worth two separate pull requests (or at the very least two commits).
1. Moving edit icons works nicely; It could be merged faster if in a separate pull request. It is worth its own ticket too.
2. The link pointing to the position does not seem to work as clicking on it doesn’t scroll to the target item. Maybe adding an highlighting border around the item at the target position would be help with finding it.

**Comment by y-young** [comment]
OK, so renaming source branch automatically closes the PR. :|

**Pull request closed without merging**
