### PR TITLE
Eslint fixes for URLCleanup test

### PR DESCRIPTION
**Pull request by reosarevok**
Includes #840 since it touches the same file and I fully expect that to be merged before this :)

### CODE REVIEW

**Comment by reosarevok** [comment]
I can maybe see the key order, although I don't particularly think having it nice and alphabetical makes it worse, but the indents just look and feel weird to me and I don't feel they provide anything of use - the file is equally readable after a6afd69f8c57b10a29457344af605b609406fb6e

**Comment by yvanzo** [comment]
Values alignment helps to compare these. For example, it is particularly helpful with comparing differences between input URL and expected output URL. If _the file is equally readable after_ (which I don't agree with), then maybe this commit is not worth it.

**Comment by reosarevok** [comment]
I feel following the same rules everywhere and the consistency that gives is enough of a reason to do it, and dislike the idea of disabling rules on a per-file basis, tbh. 

Re: indent, at the very least I'd expect to see everything unindented to the left of the file except for the key-value pairs themselves.

**Comment by yvanzo** [comment]
It doesn’t sound very rational. Ability to [disable specific eslint rules on demand](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments) is there for a reason.

**Comment by mwiencek** [comment]
So let's revert the changes to `testData` and add `eslint-disable indent, sort-keys`/`eslint-enable indent, sort-keys` comments around it? Since @yvanzo is the primary maintainer of this file I don't see an advantage in making it less readable for him.

**Comment by reosarevok** [comment]
What about now? :) 

I changed the 4 space indents to 2 spaces, but left the visual indentation untouched and the keys unsorted.

I moved a few comments that were after the first key to be on top of the first key (so https://github.com/metabrainz/musicbrainz-server/pull/844/files#diff-eb68718856b483c030b05815375ce614L3292 to https://github.com/metabrainz/musicbrainz-server/pull/844/files#diff-eb68718856b483c030b05815375ce614R3291) because that feels much more clear to me, but I can undo if desired.

**Pull request merged**
