### PR TITLE
MBS-12631: Autocomplete2: Don't show unselectable items

### PR DESCRIPTION
**Pull request by mwiencek**
https://tickets.metabrainz.org/browse/MBS-12631

This avoids showing unselectable (disabled) static items when typing by simply excluding them from being indexed.

### CODE REVIEW

**Review by reosarevok — APPROVED** [review]
Simple and does the trick. Do we want to maybe add tests for things like these? :)

**Comment by mwiencek** [comment]
> Simple and does the trick. Do we want to maybe add tests for things like these? :)

I suppose we could. :)

**Comment by mwiencek** [comment]
@brainzbot test this please

**Comment by mwiencek** [comment]
@brainzbot test this please

**Comment by mwiencek** [comment]
@brainzbot test this please

**Comment by reosarevok** [comment]
@brainzbot, retest this please

**Comment by reosarevok** [comment]
@brainzbot, retest this please

**Comment by reosarevok** [comment]
The cache pruning is failing, see Selenium result :)

**Pull request merged**
