### PR TITLE
MBS-10425: Allow rel credits for instruments

### PR DESCRIPTION
**Pull request by reosarevok**
https://tickets.metabrainz.org/browse/MBS-10425

### CODE REVIEW

**Comment by reosarevok** [comment]
Whoopsio. Done.

**Comment by yvanzo** [comment]
Where is that change visible?

**Comment by reosarevok** [comment]
Any instrument editing page, for example. instrument/b3e097c7-c167-4436-984f-5742a4542bb2/edit should exist even in the sample DB. You can just add a rel to another instrument and see if you can set credits.

**Comment by reosarevok** [comment]
Not only - I think you should also see it if you try to link an artist to an instrument, for example (with "invented" or whatnot) :) But yeah, I can see the confusion, will change wording.

**Comment by yvanzo** [comment]
> if you try to link an artist to an instrument

Yes but I’m not sure this should be allowed in the first place.

**Comment by reosarevok** [comment]
Well, we're going to need it for STYLE-480 :)

**Pull request merged**
