### PR TITLE
MBS-9907: Report for places without coordinates

### PR DESCRIPTION
**Pull request by Ge0rg3**
## [MBS-9907](https://tickets.metabrainz.org/browse/MBS-9907): New report: Places without coordinates
This commit adds support for a new daily report, which shows all the places which haven't been assigned coordinates.

https://tickets.metabrainz.org/browse/MBS-9907

I originally did this with an "annotation" column, but seeing as the number of entries with annotations is relatively low, it seemed more of an inconvenience.

The final result looks as follows:

image

### CODE REVIEW

**Comment by Ge0rg3** [comment]
@reosarevok changes made :)

**Comment by Ge0rg3** [comment]
The [new commit](https://github.com/metabrainz/musicbrainz-server/pull/762/commits/72ab4a16347d47b624cad5e4fd2a2b72bac18a4e) introduces a search button, which will take the user to a Google maps search page with all of the data in the row filled in automatically:

image

**Comment by yvanzo** [comment]
I’m not sure linking to Google Maps is appropriate here as label’s map is displayed from OpenStreetMap. @reosarevok?

**Comment by Ge0rg3** [comment]
Should I remove this for now? @reosarevok @yvanzo

**Comment by Freso** [comment]
Maybe make a "Search" button/link for OpenStreetMap instead? That way it'd still have the convenience of a one-click help to find the coordinates, but we'd also be supporting another open data project (whose data we're also consuming/using in the form of their maps). But yeah, having more text than just "Search" would probably be good. "Search OpenStreetMap" is maybe too long? It does seem like there's a lot of empty space in the columns though.

**Comment by Ge0rg3** [comment]
@Freso Cool, how about having "Search OpenStreetMap" as the column header, and then just "Search" on the buttons?

**Comment by Ge0rg3** [comment]
@yvanzo Okay, I've now committed that.

**Comment by yvanzo** [comment]
Nit-picking: you did not update latest commit message accordingly.

**Comment by Ge0rg3** [comment]
> Nit-picking: you did not update latest commit message accordingly.

Good spot, fixed.

**Comment by yvanzo** [comment]
Thank you for this additional contribution!

**Pull request merged**
