### PR TITLE
Fix margin of link action icons

### PR DESCRIPTION
**Pull request by y-young**
Before:
image

After:
image

### CODE REVIEW

**Comment by y-young** [comment]
@brainzbot Retest

**Comment by y-young** [comment]
@brainzbot Retest this please.

**Review by yvanzo — APPROVED** [review]

**Comment by yvanzo** [comment]
Tested and worked for me too. It follows PR <https://github.com/metabrainz/musicbrainz-server/pull/2219>.

**Review by reosarevok — APPROVED** [review]
Seems to work fine indeed.

**Pull request merged**
