### PR TITLE
Check for Postgresql 9.5 instead of 9.1

### PR DESCRIPTION
**Pull request by SpootDev**
Verify 9.5 instead of 9.1 version.

Sorry, didn't "test" this as my current install is pooched.  And found this while trying to unpooch it.  :)

### CODE REVIEW

**Comment by mwiencek** [comment]
Thanks. Though GitHub is showing the entire file as changed. Maybe your editor isn't configured to write unix line endings?

**Comment by SpootDev** [comment]
GAH!  Bleeping windows.......gimmie a minute to fix this.

**Comment by SpootDev** [comment]
Sorry bout that, should be ok now.

**Comment by mwiencek** [comment]
Yep, looks good now. 👍  I squashed all the commits and merged this in e8466adb86705ccb49200ce4709f453f3a44e06c.

**Pull request closed without merging**
