### PR TITLE
MBS-11353: Allow empty row in multiple select

### PR DESCRIPTION
**Pull request by reosarevok**
### Fix MBS-11353

Without this, cover art type can only be unset in an unintuitive way involving control-clicks. We used to have this, so we should readd it.

### CODE REVIEW

**Comment by jesus2099** [comment]
Are you sure this is needed and a regression?
See forum topic from MBS-11353.

**Comment by reosarevok** [comment]
Heh. Now I'm not sure. It's hard to test this because I don't have cover art set up locally, but you might be right the (horribly unintuitive) option you mention is how it used to be earlier too and this doesn't actually help :/ In which case I should drop this and make the ticket into "Add an intuitive way of blanking a multiselect"

**Comment by jesus2099** [comment]
I remember some people don't like those multi-select: https://community.metabrainz.org/t/edit-coverart-types-to-have-multiple-types/437363/6?u=jesus2099
I will link this ticket as related: https://tickets.metabrainz.org/browse/MBS-10307

**Comment by reosarevok** [comment]
Seems the TT form *did* have a blank line (I checked an old unrelated branch which still had that) so we should, in any case, bring this back to make it easier to deselect it.

**Comment by jesus2099** [comment]
Yes, then. 
Sorry for my doubts. ☺️

**Review by mwiencek — APPROVED** [review]

**Review by yvanzo — APPROVED** [review]
This change doesn’t other multi-select fields because:

From @reosarevok:
> MultipleSelectField is only used in CoverArtFields right now

And other multi-select fields not yet converted to React (attributes in relationship editor, and secondary types in release group editor) allow for empty select already.

:shipit:

**Pull request merged**
