### PR TITLE
MBS-13087: Change bitwise AND to OR for combining privileges

### PR DESCRIPTION
**Pull request by the-good-boy**
### Fix MBS-13087

The ``PUBLIC_PRIVILEGE_FLAGS `` has been wrongly constructed using the bitwise AND operator. It should be constructed using the bitwise OR operator instead.

### CODE REVIEW

**Review by kellnerd — APPROVED** [review]
LGTM as per [my comment on IRC](https://chatlogs.metabrainz.org/libera/bookbrainz/msg/5173122/) after going through the related code.
This bug probably went unnoticed so far because the privileges of a sanitized editor aren't used anywhere throughout the codebase.
The privileges only seem to be of relevance in places where an unsanitized editor instance is used, e.g. https://github.com/metabrainz/musicbrainz-server/blob/e6cf1f7377e76f7e9dfabe11d69f6dbbe8c49800/root/user/UserProfile.js#L57

**Comment by yvanzo** [comment]
@brainzbot, please add to whitelist.

**Comment by reosarevok** [comment]
This seems sensible to me. We should probably be testing this somewhere, not quite sure where though :) (seems there's no tests for `sanitizedEditor` currently?)

**Comment by reosarevok** [comment]
Pushed a second commit that adds an actual test for `sanitizedEditor` (including a test for auto-editor privs that failed before your commit but passes now).

**Review by reosarevok — APPROVED** [review]

**Comment by reosarevok** [comment]
@kellnerd did miss one use of the privileges that meant we actually had a small display bug, which this PR now fixes :)

**Review by mwiencek — APPROVED** [review]

**Pull request merged**
