### PR TITLE
MBS-9277: Add autoselect/sidebar for Mixcloud URLs

### PR DESCRIPTION
**Pull request by PROTechThor**
This PR addresses the problem in [this ticket](https://tickets.metabrainz.org/browse/MBS-9277). 
There's no autoselect/sidebar for Mixcloud URL for artists. This PR adds support for it. An entity and a test case have been added as well. The complete list of changes include:

- A new entity for mixcloud created. It has been added to the sidebar and a given a favicon.

- The URL has been cleaned up to replace http with https, as well as to make sure the domain name is lowercased. 

- A test case, in which mixcloud was added as a URL entity, and setup as a social network.

### CODE REVIEW

**Comment by yvanzo** [comment]
Thank you again for contributing! If you don't mind, I’d like to regroup your changes into logical commits before merging. I would pick your own words from the pull request description for commit messages.

**Comment by PROTechThor** [comment]
@yvanzo Sounds good. :D

**Comment by yvanzo** [comment]
@brainzbot, please test this.

**Comment by yvanzo** [comment]
@brainzbot test this please.

**Comment by yvanzo** [comment]
@Ge0rg3 It actually compares this URL with the output of the `clean` function called with the same URL. It also checks `socialnetwork` is automatically selected for this URL in an artist editing form. See https://github.com/metabrainz/musicbrainz-server/commit/dcabded48be065374c55bfb789ad588daa363729 about specifying tests. This test (and the `clean` function) can be improved indeed so as to additionally test scheme normalization (to `https`) and subdomain normalization (to `www`).

**Pull request merged**
