### PR TITLE
MBS-12403: Generate diagrams for the database schema documentation

### PR DESCRIPTION
**Pull request by yvanzo**
# Problem

MBS-12403: Some diagrams used in [database schema documentation](https://musicbrainz.org/doc/MusicBrainz_Database/Schema) of the MusicBrainz database are obsolete or incomplete thus have to be updated after [v-2022-05-16-schema-change release](https://blog.metabrainz.org/2022/05/16/musicbrainz-schema-change-release-2022-05-16-with-upgrade-instructions/).

Furthermore, the tool that was used to draw those diagrams is not maintained anymore.

# Solution

Have a new script that:
- Parse our `CreateTables.sql` files the same way we already do to generate `DropTables.sql` and other SQL files.
- Generate DOT files based on a diagram description stored in a JSON file.
- Convert these files to SVG (which is zoom-able) for inclusion in a webpage.

See commits’ messages for details.

# Actions (before merging)

* [x] Manually separate overlapping lines using the Bézier curve tool of Inkscape.
* [x] Install ImageMagick for MediaWiki to generate thumbnails of SVG files.
* [x] Update https://wiki.musicbrainz.org/MusicBrainz_Database/Schema wiki page along with updating/uploading the following files:
  * [x] https://wiki.musicbrainz.org/File:cdstubs.png replaced with [`cdstub_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/cdstub_details.svg)
  * [x] https://wiki.musicbrainz.org/File:cover_art.png replaced with [`cover_art_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/cover_art_details.svg)
  * [x] https://wiki.musicbrainz.org/File:ngs.png replaced with [`entity_network_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/entity_network_details.svg)
  * [x] https://wiki.musicbrainz.org/File:ngs-ars.png split into:
    * [x] [`relationship_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/relationship_details.svg)
    * [x] [`relationship_overview.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/relationship_overview.svg)
  * [x] New files:
    * [x] [`entity_network_overview.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/entity_network_overview.svg)
    * [x] [`area_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/area_entity_details.svg)
    * [x] [`artist_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/artist_entity_details.svg)
    * [x] [`event_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/event_entity_details.svg)
    * [x] [`genre_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/genre_entity_details.svg)
    * [x] [`instrument_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/instrument_entity_details.svg)
    * [x] [`label_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/label_entity_details.svg)
    * [x] [`place_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/place_entity_details.svg)
    * [x] [`recording_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/recording_entity_details.svg)
    * [x] [`release_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/release_entity_details.svg)
    * [x] [`release_group_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/release_group_entity_details.svg)
    * [x] [`series_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/series_entity_details.svg)
    * [x] [`url_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/url_entity_details.svg)
    * [x] [`work_entity_details.svg`](https://github.com/yvanzo/musicbrainz-server/blob/mbs-12403-diagrams/docs/database_schema_diagrams/work_entity_details.svg)

# Action (after merging)

1. Update the transclusion for https://musicbrainz.org/doc/MusicBrainz_Database/Schema website page.

### CODE REVIEW

**Comment by yvanzo** [comment]
Just squashed the fixes for coding style and file permissions.

**Comment by yvanzo** [comment]
Note: Initial feedback has been given as comments to MBS-12403.

**Review by mwiencek — COMMENTED** [review]
I'm very happy that we'll have a way to automatically generate these from the SQL.  Nice work!

> [about musicbrainz_with_cover_art] Exhaustive diagram, it just shows the complexity of the database schema but it isn’t meant to be actually readable otherwise.

It really is impossible to read because all of the lines overlap and can't be followed to their destination.  So I wonder if we should even include this, because it can't be used other than glancing at it once, thinking "yup, this is complex," and closing it permanently. :)  Maybe we should just focus on the smaller subgraphs and say a "complete" SVG is unreasonable to provide.

My only other feedback after reading the ticket is that I agree the gradients are a bit much for me.  You are probably right that pure white would be worse, but perhaps we could go with more neutral gradient colors like light gray/blue.

**Comment by yvanzo** [comment]
Dropped the overloaded diagram in commit https://github.com/metabrainz/musicbrainz-server/pull/2570/commits/33e6a328ee6bda692165f922ba5599917002caed and pastelized background colors in later commits https://github.com/metabrainz/musicbrainz-server/pull/2570/commits/545f8138cd00bd0f42f5b896ae7179cf1844f2cb and <https://github.com/metabrainz/musicbrainz-server/pull/2570/commits/d0872dfb100e97259fccf3a6df65cbb0cc951bac>. I did not use “light gray/blue” as it would not allow to distinguish the CAA schema from the MB schema.

Added a post-processing step to manually separate overlapping lines using the Bézier curve tool of Inkskape.

**Review by mwiencek — APPROVED** [review]
The lighter colors are a bit easier on the eyes for me.

**Review by reosarevok — APPROVED** [review]
This is certainly more readable than before. I still find the old style clearer, but I can live with this.

**Comment by yvanzo** [comment]
Beyond squashing previous fix commits, I made the following changes in separate fix commits:
- Normalize and optimize the SVG using Scour
- Add a couple of missing tables (`series_ordering_type` and `work_language`) to the large diagram of tables unique to some entity types
- Remove private tables (`work_rating_raw` and `work_tag_raw`) from the diagram for `work` entity type.

Please let me know if some tables or diagrams are still missing or unneeded. Afterwards I will proceed to separating lines using Inkscape.

**Comment by yvanzo** [comment]
- Reorganized the code by replacing the system calls with a `Makefile` which allows to:
  * regenerate the needed files only (that is without overwriting the SVG files that have been manually edited),
  * normalize the manually edited files with a single command `make normalized.
- Reorganized files layout by moving diagrams under subdirectories `source` (for JSONs), `graphs` (for DOTs), `images` (for SVGs).
- Added a `README.md` file to document both the files layout and the diagram generation process including the manual editing.
- Added diagrams for all primary entity types.
- Manually edited SVG files to remove unneeded line overlaps

Currently trying to upload SVG files to the wiki, but it seems that it requires installing ImageMagick first. Updating the PR’s description.

**Comment by yvanzo** [comment]
- Installed ImageMagick for MediaWiki to generate thumbnails of SVG files.
- Replaced old diagrams with new ones in version 75903, see [diff](https://wiki.musicbrainz.org/index.php?title=MusicBrainz_Database/Schema&diff=75903&oldid=75807).
- Checked that previous files are not used anywhere else (but in a draft by Mineo).

**Comment by yvanzo** [comment]
- Applied the typo fix https://github.com/metabrainz/musicbrainz-server/pull/2570/commits/e1502b3d338bdfa8d7277a12dcdd0f1a6e347fd5.
- Uploaded all diagrams for primary entity types in version 75915, see [diff](https://wiki.musicbrainz.org/index.php?title=MusicBrainz_Database/Schema&diff=75915&oldid=75903), but genre and instrument are still missing, added to the PR’s description.
- Improved the layout using tables

**Comment by yvanzo** [comment]
- Squashed commit https://github.com/metabrainz/musicbrainz-server/pull/2570/commits/19aaa001945542d53bfbcdf589e0a3bb69f19fae for genre and instrument
- Uploaded these two diagrams and used these in the Schema documentation page, see [diff](https://wiki.musicbrainz.org/index.php?title=MusicBrainz_Database/Schema&diff=75920&oldid=75917).
All set for merging now.

**Comment by yvanzo** [comment]
Also installed generation dependencies in development setup: https://github.com/metabrainz/musicbrainz-docker/commit/ecb6257866035213aba4ebef837f818a371993f3

**Pull request merged**
