### PR TITLE
MBS-12334: Collapse ISRCs and ISWCs when there are too many

### PR DESCRIPTION
**Pull request by reosarevok**
### Implement MBS-12334

### CODE REVIEW

**Review by yvanzo — APPROVED** [review]
Tested with the example given in the linked ticket: https://musicbrainz.org/recording/21bc4ba0-3b43-43b8-9702-f5f066c894e8

I noticed that the inserted “show … more” (ISRCs) paragraph has more vertical spacing than the “show … more” (Release events) list item has in release sidebar (for example see <https://musicbrainz.org/release/1173188d-3fa7-416b-8c5e-8c5e75872748>). It should probably be a `<div>` tag rather than a `<p>` tag. Not sure how to do that though.

Otherwise the code looks good to me and the overall is already an improvement over the current display.

**Comment by reosarevok** [comment]
Changing it to <div> is trivial but it didn't seem to help much, so will leave as-is for now.

**Comment by yvanzo** [comment]
@reosarevok: I used the inspector tool to change `p` to `div` and it did solve the issue locally. Can you please provide the trivial change you tried?

**Comment by reosarevok** [comment]
That'd be just changing `p` to `div` on https://github.com/metabrainz/musicbrainz-server/blob/83fd1488c90e3d7c9d363f97cfccc0aa6d614368/root/static/scripts/common/components/IsrcList.js#L45 (and I guess `IswcList` too) but I didn't really notice any significant difference. Maybe I'm blind though, if you find it differs just push the change straight to master if you want :)

**Comment by yvanzo** [comment]
This is not changing the `p` around “(show … more)”.

**Comment by yvanzo** [comment]
Was probably a cache issue, probably not the flow type issue. Anyway, it does the intended change, see the pull request #2612.

**Pull request merged**
