### PR TITLE
MBS-10304: Reallow special codes as editor language

### PR DESCRIPTION
**Pull request by reosarevok**
https://tickets.metabrainz.org/browse/MBS-10304

Reverting commit b645483e87b0a08f150a59d813fe807245680d08 as requested
by several editors, including our community manager.

### CODE REVIEW

**Comment by yvanzo** [comment]
Is that a joke?

**Comment by reosarevok** [comment]
Why would it be? If the people involved with community stuff ask for this to be brought back for the community, why shouldn't we do it?

**Comment by yvanzo** [comment]
I genuinely thought that it was a joke, ticket included.

**Comment by reosarevok** [comment]
Changed this to still disallow `mul`, as per comments on the ticket :)

**Comment by mwiencek** [comment]
@yvanzo thoughts on this now?

**Comment by yvanzo** [comment]
Per yesterday’s discussion, it would be to avoid heterogeneous styling. Maybe having a style similar to `ar-desc` class, like in pull request https://github.com/metabrainz/musicbrainz-server/pull/1217, would do?

**Comment by mwiencek** [comment]
Don't think it's related - at least I can't reproduce the issue locally or by connecting to the pink or williams DBs.

**Comment by yvanzo** [comment]
For the record, that crash was due to a language with frequency set to 3 in the test database. Even though restored values still make no sense to me, these cannot be mistakenly selected by editors at least.

**Pull request merged**
