### PR TITLE
MBS-8801: Fix spurious group-with-gender error

### PR DESCRIPTION
**Pull request by uklauer**
An artist edit can remove the artist’s type or gender by setting it to `NULL` (represented by `undef` in Perl). On the other hand, it can leave fields unchanged (represented in Perl by the absence of a hash entry). Because of a test for definedness instead of existence of a key before falling back to the current state of the artist, it could happen that an edit was rejected for resulting in a group artist with a gender when that was not actually the case.

Includes a test.

### CODE REVIEW

**Comment by uklauer** [comment]
The test itself is untested, unfortunately, because the test database on rika is broken.

**Comment by mwiencek** [comment]
Test database should work on rika now. And you should have permission to run create_test_db.sh, if you need it.

I ran the test locally and there was a failure, so needs checking in any case. :)

**Comment by uklauer** [comment]
OK, fixed.

**Comment by mwiencek** [comment]
Thank you :shipit:

**Pull request merged**
