### PR TITLE
MBS-9577: Update Google custom search engine to API v2.0

### PR DESCRIPTION
**Pull request by navap**

### CODE REVIEW

**Comment by yvanzo** [comment]
@brainzbot, add to whitelist.

**Comment by navap** [comment]
Disclaimer: **I have not tested this patch.** It's just a JS change, but I have no idea what the end result is going to be.

Can someone please test prior to merging in.

Items I think need testing:
- Initiate search [via the search form](https://musicbrainz.org/search?query=artist&type=doc&method=indexed#gsc.tab=0&gsc.q=artist&gsc.page=1)
- Initiate search [via the inline Google form](https://musicbrainz.org/doc/Artist)
- Google form UI - prevent [this ugly UI](https://imgur.com/0ewpwZr)

**Comment by yvanzo** [comment]
It worked for search only typed into the form _Google Custom Search_ at the page _Documentation Search_.

Deploying https://github.com/metabrainz/musicbrainz-server/commit/abcbe006e76ea5ba174b5ae5955c705cedc5c0f8 enables initiating search from URL query parameter `query` (instead of default `q`). That was the only missing bit to initiate search from every other form.

Handling of search history with URL fragment is back since https://github.com/metabrainz/musicbrainz-server/commit/9002e33f5518addca0024fd1b951597c7df8cb8d.

Finally, the UI is still _ugly_, but it can probably be improved using the Google CSE control panel.

**Comment by yvanzo** [comment]
Fixed the CSS issue with https://github.com/metabrainz/musicbrainz-server/commit/c043d20eae1b56070923966054d56c75a556a460.

**Pull request merged**
