### PR TITLE
MBS-8994: Allow &dismax=true in search queries

### PR DESCRIPTION
**Pull request by mwiencek**
See the ticket for details.

### CODE REVIEW

**Comment by gentlecat** [comment]
What's dismax and what does it change? A bit unclear to me from the description in that ticket.

**Comment by gentlecat** [comment]
LGTM

**Comment by mwiencek** [comment]
> What's dismax and what does it change? A bit unclear to me from the description in that ticket.

My understanding comes from https://cwiki.apache.org/confluence/display/solr/The+DisMax+Query+Parser which says:

> The DisMax query parser is designed to process simple phrases (without complex syntax) entered by users and to search for individual terms across several fields using different weighting (boosts) based on the significance of each field.

You can see that in the code for our search server, the normal artist search (with dismax=false) searches the artist name, aliases, and sort name fields, presumably with equal weightings: https://bitbucket.org/metabrainz/search-server/src/2eb1597bfbf1c9d1dfc52e69988d78e29dc8976f/servlet/src/main/java/org/musicbrainz/search/servlet/ArtistSearch.java?at=master&fileviewer=file-view-default#ArtistSearch.java-24

With dismax=true, it also searches the artist name with accents included (in addition to the above fields), but with different weightings for each field: https://bitbucket.org/metabrainz/search-server/src/2eb1597bfbf1c9d1dfc52e69988d78e29dc8976f/servlet/src/main/java/org/musicbrainz/search/servlet/ArtistDismaxSearch.java?at=master&fileviewer=file-view-default#ArtistDismaxSearch.java-13

The trade-off, as I understand it, is that you can only search for single phrases with dismax=true, not complex expressions with different field terms, boolean logic, etc.

**Comment by gentlecat** [comment]
And weights are specified in a second argument to `DismaxAlias.AliasField`, right?

**Comment by mwiencek** [comment]
That's what I gather from https://bitbucket.org/metabrainz/search-server/src/2eb1597bfbf1c9d1dfc52e69988d78e29dc8976f/servlet/src/main/java/org/musicbrainz/search/servlet/DismaxAlias.java?fileviewer=file-view-default#DismaxAlias.java-63 (although it's called "boost" there).

**Pull request merged**
