### PR TITLE
MBS-10364 (II): Convert release merge page to React

### PR DESCRIPTION
**Pull request by reosarevok**
### Implements the end of MBS-10364

### CODE REVIEW

**Review by mwiencek — APPROVED** [review]
I rebased this & fixed a minor issue where the release radio button wouldn't remember its selection.  Tested both merge strategies locally.

**Comment by reosarevok** [comment]
Did you also test bad recording merges and stuff like that? :)

**Comment by mwiencek** [comment]
I tested merging two releases with different track/recording ACs, and the warning message does show up if I select the "merge" merge strategy.  (There is an existing Selenium test for this, BTW.)  I was also able to trigger the "track counts on at least one set of corresponding mediums do not match" error message.  I didn't test the others, but I suspect they work since they're also produced by `Data::Release::can_merge`.

**Comment by reosarevok** [comment]
In that case, feel free to merge if you feel this is ready :)

**Comment by mwiencek** [comment]
@brainzbot retest this please

**Pull request merged**
