### PR TITLE
Generate all URL validation rules

### PR DESCRIPTION
**Pull request by y-van-z**
Previously, old-fashion hand-coded `validationRules` coexisted with generated ones.

This pull request replaces all hand-coded `validationRules` by `CLEANUPS.*.validate` functions which are used to generate new `validationRules` instead.

Incidentally, validation rules have been tightened for Bandcamp, IMDb, Amazon, YouTube, VGMdb, AllMusic, Discogs, SoundCloud, VIAF, Myspace, Wikipedia, and BBC Music URLs.

Additionally, clean-up has been added for BBC Music URLs and VGMdb event URLs.

It is a revision of PR #366 by @uklauer, see [changes made](https://github.com/y-van-z/musicbrainz-server/commits/validation_rules_wiping) since then.

### CODE REVIEW

**Comment by y-van-z** [comment]
Fix failed test “relationshipEdit edit for external link is generated for existing release” in [build #119](https://ci.metabrainz.org/job/musicbrainz-server/119/) with f3eceedf407765c78fa703b9aa4c119768291297 and add URLCleanup test for it in 99360b037a2f993f9334b3ed7745e349218aee78.

**Comment by y-van-z** [comment]
Force pushed to reset authors since I changed all commit messages.

**Comment by y-van-z** [comment]
Force pushed (again) to reset author since I changed all commit messages but https://github.com/metabrainz/musicbrainz-server/pull/427/commits/f7f2a373c81e63d6a444bf82176c90f4f6ff7746.

**Comment by mwiencek** [comment]
Awesome, thank you (@uklauer too). :shipit:

**Pull request merged**
