### PR TITLE
Delete ly.png and add new Libyan flag

### PR DESCRIPTION
**Pull request by caroline-gschwend**
newlibya

Replace outdated Libyan flag file with new version.

### CODE REVIEW

**Comment by gentlecat** [comment]
Hey, it looks like you forgot to add new one.

**Comment by caroline-gschwend** [comment]
I'm having trouble adding the new image file.

**Comment by gentlecat** [comment]
What's the problem?

**Comment by caroline-gschwend** [comment]
The new file button does not allow me to add an image at all.

**Comment by uklauer** [comment]
That’s better. :-)

**Comment by gentlecat** [comment]
Perfect. :+1:

**Comment by mwiencek** [comment]
:shipit:

**Pull request merged**
