### PR TITLE
Fix TouhouDB URL handler (.com instead of .net) originally added for MBS-9694

### PR DESCRIPTION
**Pull request by riipah**
TouhouDB regex should be touhoudb.com, not touhoudb.net

### CODE REVIEW

**Comment by yvanzo** [comment]
@brainzbot test this please.

**Comment by yvanzo** [comment]
Thank you for reporting and fixing this bug!

(I rewrote the commit message, simplified regular expressions and updated tests.)

**Comment by riipah** [comment]
thanks! No problem.

**Comment by riipah** [comment]
Can I ask, how soon will it be deployed to production?

**Comment by yvanzo** [comment]
This will be deployed to beta this week.

**Comment by yvanzo** [comment]
@riipah, it is in beta.

**Comment by riipah** [comment]
Seems to be working now, thanks!

**Pull request merged**
