### PR TITLE
Refactor: Fix role’s name for pending edits

### PR DESCRIPTION
**Pull request by yvanzo**
# Problem

Role’s name `Editable` wrongly suggested that entity could be directly edited, whereas it just brings pending edits which can be made to a connected editable entity instead.

# Solution

Thus renaming as `PendingEdits`.

# Checklist for author

* [x] Fix Moose code (`MusicBrainz::Server::Entity`)
* [x] Locate and fix other inappropriate occurrences of `Editable`

### CODE REVIEW

**Comment by reosarevok** [comment]
Renamed `Editable` also in `Data::` and in Flow now.

**Comment by reosarevok** [comment]
@brainzbot, retest this please

**Comment by yvanzo** [comment]
Rephrased the commit messages following our discussion on IRC. Also rebased on master branch’s latest HEAD.

**Comment by yvanzo** [comment]
Approved twice on IRC.

**Pull request merged**
