### PR TITLE
MBS-9706: Normalize OCRemix URLs (including HTTPS)

### PR DESCRIPTION
**Pull request by reosarevok**
### Implement MBS-9706

Validation is MBS-7674 but there's (old) discussion there about whether /remix pages should be freedownload instead. Will do that later once we have more feedback.

### CODE REVIEW

**Review by yvanzo — COMMENTED** [review]
The ticket is about normalization, whereas this pull request is about `https` only.

**Comment by reosarevok** [comment]
It's not though, it also has `([^\/?#]+).*$` to drop fragments and whatnot. Shouldn't that do the trick?

**Review by yvanzo — CHANGES_REQUESTED** [review]
Why does it now contain unrelated commits for Overture? It should probably be rebased on `master`.

**Comment by reosarevok** [comment]
That's unrelated and that's why it is in a new commit, but it's just a small bug I noticed when fixing this. I can give it a ticket number if you feel it's worth it.

**Comment by yvanzo** [comment]
@reosarevok: Because the first commit message, I stopped reviewing after it. I did not see there were two commits or OCRemix. Maybe add part numbers `(1/2)`, `(2/2)` next to the ticket number in commit message?

**Review by mwiencek — APPROVED** [review]

**Review by yvanzo — APPROVED** [review]
Thank you @reosarevok!

**Pull request merged**
