### PR TITLE
MBS-12964: Allow specifying dates when batch-creating works

### PR DESCRIPTION
**Pull request by reosarevok**
### Fix MBS-12964

# Problem
IIRC in the previous editor it was possible to specify the dates to be used for the recording-work rels when batch-creating works. In the current one it's not, so if you want to add dates you have to add the works first, then edit the rels by hand one by one.

# Solution
This just basically reuses `DialogDatePeriod` in exactly the same way `RelationshipDialogContent` uses it. Quite a bit of duplication, but we already had that for attributes. Still, might be worth to refactor it in a subsequent commit.

# Testing
Manually, by batch-adding some works, and checking that invalid date periods block submitting the dialog.

### CODE REVIEW

**Comment by reosarevok** [comment]
@brainzbot, retest this please

**Comment by reosarevok** [comment]
@mwiencek: selenium failure seems legit here :)

**Comment by reosarevok** [comment]
@brainzbot, retest this please

**Comment by reosarevok** [comment]
@brainzbot, retest this please

**Review by yvanzo — APPROVED** [review]
The code looks good. Tested manually too. Not sure if it is worth waiting for an update of `Release_Relationship_Editor` Selenium test to merge this pull request.

**Review by mwiencek — APPROVED** [review]

**Pull request merged**
