### PR TITLE
MBS-12721: Normalize 45cat.com/45worlds.com links to HTTPS

### PR DESCRIPTION
**Pull request by reosarevok**
### Implement MBS-12721

# Problem
Both sites now redirect to HTTPS (although they still show HTTP in a few sharing buttons, probably an oversight - see ticket comments).

# Solution
I'm normalizing both to HTTPS now. I made changes so that both HTTP and HTTPS still work with 45worlds' `sidebar_name` construction since there's probably going to be HTTP links for a while anyway, but made sure we link to them all as HTTPS with `override href_url`.

# Testing
Manually for the override (`/release-group/fe2e55f1-6711-4ab4-b3b3-b9ce7716f667`), updated the tests for the normalization.

### CODE REVIEW

**Review by yvanzo — COMMENTED** [review]
I left a comment to the ticket about the pertinence of this change.

The patch was also lacking changes to `URL::45worlds` for sidebar name display.

**Comment by reosarevok** [comment]
Good catch, I completely missed that :)

**Review by yvanzo — COMMENTED** [review]
[https://github.com/metabrainz/musicbrainz-server/pull/2395#discussion_r1084394722](https://github.com/metabrainz/musicbrainz-server/pull/2395#discussion_r1084394722) recalled me of this: Maybe have an `href_url`in both `URL::45cat` and `URL::worlds`?

**Comment by reosarevok** [comment]
You mean an 

```
override href_url => sub {
    shift->url->as_string =~ s{^http:}{https:}r;
};
```

or something more specific?

**Comment by yvanzo** [comment]
It looks fine.

**Review by yvanzo — APPROVED** [review]
LGTMBDNT

**Pull request merged**
