### PR TITLE
Perl::Critic: Remove unused variables and imports

### PR DESCRIPTION
**Pull request by reosarevok**
On top of https://github.com/metabrainz/musicbrainz-server/pull/2283

### CODE REVIEW

**Comment by reosarevok** [comment]
@brainzbot, retest this please

**Comment by reosarevok** [comment]
@brainzbot, retest this please

**Comment by reosarevok** [comment]
@brainzbot, retest this please

**Comment by mwiencek** [comment]
@brainzbot test this please

**Comment by mwiencek** [comment]
@brainzbot test this please

**Review by mwiencek — APPROVED** [review]

**Pull request merged**
