### PR TITLE
MBS-12924: Fix page freeze after selecting a link type on Android

### PR DESCRIPTION
**Pull request by mwiencek**
# Fix MBS-12924

## Problem

Selecting a link type in the relationship dialog on Android freezes the page.

## Solution

The `set-recent-items` dispatch causes an infinite loop of re-renders in Chrome on Android. Delaying the dispatch fixes it. I haven't determined why this doesn't occur on desktop, because the React internals are quite opaque to me.

The `cancelled` addition isn't strictly needed, but it's always a good idea to clean up your effects.

## Testing

Tested manually in the Android Emulator.

### CODE REVIEW

**Review by reosarevok — APPROVED** [review]
Tested on test.mb on both Android and PC, works on both now AFAICT.

**Comment by mwiencek** [comment]
@brainzbot test this please

**Comment by reosarevok** [comment]
@brainzbot, retest this please

**Review by reosarevok — CHANGES_REQUESTED** [review]
Selenium error is "Cannot read properties of undefined (reading 'setInputValueForReact')" so clearly that's connected to the latest changes. Is there a specific way we should be testing the bigger changes in the last commit, by the way?

**Comment by mwiencek** [comment]
> Selenium error is "Cannot read properties of undefined (reading 'setInputValueForReact')" so clearly that's connected to the latest changes.

Should be a simple fix at least. I got so unlucky with the number of difficult and novel errors triggered by this PR!

> Is there a specific way we should be testing the bigger changes in the last commit, by the way?

That affects any case where the menu would be shown without performing a search. So:

 * Focusing the input when it's empty or when there was a previous search performed without an item being selected.
 * Pressing the down arrow.
 * Clicking the search icon.

**Comment by reosarevok** [comment]
@brainzbot, retest this please

**Comment by mwiencek** [comment]
With the latest commit ("Consistently serialize id as a number") the failing test passes for me locally three tries in a row. (Additionally, the release editor doesn't even use Autocomplete2 yet, so I'm not sure what's going on there.) I'll ask Jenkins again.

@brainzbot test this please

**Comment by mwiencek** [comment]
Test are passing now, and I've tested this a bunch more locally, so I think it's fine to try it on beta. If it causes any new autocomplete regressions I'll add some tests for those.

**Pull request merged**
