### PR TITLE
a_upd_release_event: check for changes before doing work

### PR DESCRIPTION
**Pull request by mwiencek**
Avoid re-calculating `*first_release_date` data if the release event didn't actually change.

This can happen if the trigger fired on the `release_country` table and only the country changed. (Rather than checking for that, it's still correct to test the data we're concerned about: `UPDATE` triggers fire even when no data changed.)

Additionally, make sure we're only calling `set_release_first_release_date` once if the release column is unchanged.  (This would occur on merges, and probably no other time.)

### CODE REVIEW

**Comment by mwiencek** [comment]
I noticed this while adding CAA triggers on the `release_first_release_date` table (which I don't want to fire unnecessarily).

**Review by reosarevok — APPROVED** [review]
Has this shown to be pretty slow or? Anyway, seems sensible enough, AFAICT.

**Comment by mwiencek** [comment]
> Has this shown to be pretty slow or? Anyway, seems sensible enough, AFAICT.

No, but it might trigger unnecessary updates on the `release_first_release_date` table like I mentioned above (which could push unnecessary updates to the artwork indexer).

> Do we have pgtap tests for any of these?

Yes: t/pgtap/first_release_dates.sql

**Review by yvanzo — APPROVED** [review]
(need rebasing)

**Pull request merged**
