### PR TITLE
MBS-4159: Display links of Vimeo in sidebar

### PR DESCRIPTION
**Pull request by dpmittal**
I have changed the following files to display links of Vimeo in the sidebar .
Issue Link : http://tickets.metabrainz.org/browse/MBS-4159

### CODE REVIEW

**Comment by y-van-z** [comment]
LGTM. (GCI task approved.) Thanks!

**Comment by mwiencek** [comment]
Just one thing, can you include the ticket # in the commit title like you did in the pull request title? It's really useful for people looking through the history.

**Comment by dpmittal** [comment]
@mwiencek I have updated the commit message

**Comment by uklauer** [comment]
And Could You Perhaps Also Fix The Capitalization? 8) I.e. lowercase `links` and `sidebar`.

**Comment by dpmittal** [comment]
@uklauer I have fixed capitalization in PR link and commit title

**Pull request merged**
