### PR TITLE
MBS-13778: Updated Patreon logo

### PR DESCRIPTION
**Pull request by divyansh351**
# Problem
Update the Patreon logo used in the sidebar
MBS-13778

# Solution
Changed the Patreon logo to the newer one as in [here](https://news.patreon.com/articles/patreon-redesigned)

# Testing
None

### CODE REVIEW

**Review by yvanzo — APPROVED** [review]
Hi @divyansh351, thank you for this contribution. Please fix the typo (on _Patreon_) in the commit message if possible. It is good to go otherwise.

**Comment by divyansh351** [comment]
Hi @yvanzo , I have fixed the typo, thank you.

**Comment by yvanzo** [comment]
Hi @divyansh351, you fixed the pull request’s title, that’s great. You didn’t fix the **commit message** though. See https://github.com/metabrainz/musicbrainz-server/pull/3382/commits and https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Comment by divyansh351** [comment]
Hi @yvanzo, the commit message is fixed now, sorry for the misunderstanding. Thanks a lot for pointing out.

**Comment by yvanzo** [comment]
You are very welcome. Thanks again!

**Pull request merged**
