### PR TITLE
MBS-13538: Removing all rows in the artist credit editor makes it disappear

### PR DESCRIPTION
**Pull request by mwiencek**
# Problem

See the description / animated GIF in MBS-13538.

# Solution

Moving the `firstNameAutocomplete` assignment to prevent executing `newNames[0].artist` on an array of length 0 is sufficient to fix the bug. However, I also made it so that you can't remove the last remaining (non-removed) AC name row; instead, clicking the remove button will simply clear it.

# Testing

Tested manually, plus added a Selenium test.

### CODE REVIEW

**Comment by reosarevok** [comment]
a409c9935c40ae24f78449343bbc100ee95bf3a0 makes sense to me, but it means that it's not actually doable to undo the "removal" of that last row, unless with all others. Is this something we can maybe avoid?

**Comment by reosarevok** [comment]
When testing, it seems removing the last row makes the recent items no longer appear for the now empty artist input, at least until I type something. That's not consistent with the empty input after first opening the editor, which immediately displays recent items.

**Comment by mwiencek** [comment]
>  When testing, it seems removing the last row makes the recent items no longer appear for the now empty artist input, at least until I type something. That's not consistent with the empty input after first opening the editor, which immediately displays recent items.

This should now be fixed.

> https://github.com/metabrainz/musicbrainz-server/commit/a409c9935c40ae24f78449343bbc100ee95bf3a0 makes sense to me, but it means that it's not actually doable to undo the "removal" of that last row, unless with all others. Is this something we can maybe avoid?

I'm not sure how best to solve this; we could get rid of the inline undo buttons and add a general undo button below, and keep track of the complete undo history; or we could display the inline undo button if the last row item is specifically cleared, and then revert it back to a remove button if it's changed again after being cleared? Neither option is trivial and the latter seems kind of weird. I'd be more inclined to just disable the remove button entirely for the last row.

**Comment by reosarevok** [comment]
Just removing removal entirely seems fine to me TBH. I don't think anyone expects being able to remove it anyway.

**Comment by mwiencek** [comment]
> Just removing removal entirely seems fine to me TBH. I don't think anyone expects being able to remove it anyway.

OK, now it just hides the "X" button if there is only one non-removed row remaining.

**Comment by reosarevok** [comment]
This seems a lot better now. Just realized though that removing then undoing seems to lose the join phrases - is this avoidable? Rather, it changes join phrases automatically on neighbour entities after removal which seems confusing - I would expect that to happen only by user choice - especially if undoing does not bring it back. I was testing with `/release-group/699b7364-e492-470a-a919-e2b637103236/edit`

**Comment by mwiencek** [comment]
> This seems a lot better now. Just realized though that removing then undoing seems to lose the join phrases - is this avoidable? Rather, it changes join phrases automatically on neighbour entities after removal which seems confusing - I would expect that to happen only by user choice - especially if undoing does not bring it back. I was testing with /release-group/699b7364-e492-470a-a919-e2b637103236/edit

That does seem wrong, but I think it's already an issue in production, right?

The `automaticJoinPhrase` code has always been slightly problematic, and I wouldn't mind working on this in a separate pull request if we have a clear idea for how the logic should work.

**Comment by reosarevok** [comment]
I guess so, so yeah let's not block this branch with it.

**Comment by mwiencek** [comment]
@brainzbot test this please

**Pull request merged**
