### PR TITLE
MBS-8957: Update SecondHandSongs icon and add BBC logo in the sidebar

### PR DESCRIPTION
**Pull request by y-van-z**
http://tickets.musicbrainz.org/browse/MBS-8957

### CODE REVIEW

**Comment by gentlecat** [comment]
@brainzbot, ok to test.

**Comment by uklauer** [comment]
You need to add the BBC to `root/static/styles/favicons.less`, too.

**Comment by uklauer** [comment]
Wondering … is there a particular reason not to take the available 32 px icons?

**Comment by y-van-z** [comment]
For secondhandsongs, it lowers the bits size from 2127 to 442.
For BBC, not really, I just thought it's always displayed at 16px size.

**Comment by y-van-z** [comment]
Just in case, I created an alternative branch with 32px icons at https://github.com/y-van-z/musicbrainz-server/tree/mbs-8957-32px

**Comment by mwiencek** [comment]
Yeah, let's always use 32px if they're available, since 16px looks fuzzy on hi-res displays. You can just force-push the 32px commits to this branch.

**Comment by uklauer** [comment]
Note that, in the 32-px branch, you need to add *32* for the BBC to the stylesheet.

**Comment by y-van-z** [comment]
@uklauer @mwiencek That was not a graceful PR, but everything should be in place now. :smile:

**Comment by gentlecat** [comment]
@brainzbot, add to whitelist.

**Comment by gentlecat** [comment]
Merged in https://github.com/metabrainz/musicbrainz-server/commit/030f9cc6dce2d2fa4017471ae93a9e3a2a017df9.

**Pull request closed without merging**
