### PR TITLE
MBS-8824: Update the rateyourmusic logo used in the sidebar

### PR DESCRIPTION
**Pull request by y-van-z**
http://tickets.musicbrainz.org/browse/MBS-8824

### CODE REVIEW

**Comment by gentlecat** [comment]
@brainzbot, ok to test.

**Comment by y-van-z** [comment]
Just in case, I created an alternative branch with 32px icons at https://github.com/y-van-z/musicbrainz-server/tree/mbs-8824-32px for https://github.com/metabrainz/musicbrainz-server/pull/301#issuecomment-222272570

**Comment by gentlecat** [comment]
LGTM

**Comment by uklauer** [comment]
The diff looks OK, but four commits (including a criss-cross merge) is a bit much here. Could you rebase/squash it into one, please?

**Comment by gentlecat** [comment]
Squashed and merged in 7648b1fdf26ef2017c8e4e21f360acd2b2e8554a.

**Pull request closed without merging**
