### PR TITLE
Update SIR and MB Solr in CI tests

### PR DESCRIPTION
**Pull request by yvanzo**
# Problems

* SIR `2.y.z` is not compatible with MB DB schema sequence `27`
* Tests do not use the same version of MB Solr as in production
* Chrome Driver is outdated compared to the current stable

As a result, Selenium tests are failing.

# Solution

* Rebuild cpanm snapshot for the occasion
* Bump MB Solr version to `3.2.4` ([release notes](https://github.com/metabrainz/mb-solr/releases/tag/v3.4.2))
* Bump Chrome Driver version to `101.0.4951.41`
* Bump SIR version to `3.0.0` ([release notes](https://github.com/metabrainz/sir/releases/tag/v3.0.0))
  Fix installing its requirements:
  * Self-upgrade PIP to the latest `20.3.4` version supporting Python 2
  * Install `typing` package which seems to be now missing otherwise
  * Fix the URL to install `ultrajson` from its git repository
* Refer to a new tag for the `musicbrainz-tests` image in CircleCI config (which is also used by Jenkins for Selenium tests)

# Checklist for author

* [x] Build and push a new image `metabrainz/musicbrainz-tests:v-2022-05.4` built from this pull request.

### CODE REVIEW

**Comment by yvanzo** [comment]
@brainzbot retest this please

**Comment by yvanzo** [comment]
Selenium tests most often pass ([build 7298](https://ci.metabrainz.org/job/musicbrainz-server/7298/)) but CAA test keeps sometimes failing ([build 7297](https://ci.metabrainz.org/job/musicbrainz-server/7297/)), as it was before I guess.

**Review by mwiencek — APPROVED** [review]

**Review by reosarevok — APPROVED** [review]
LGTM now, and tests pass, so :)

**Comment by yvanzo** [comment]
Finally managed to rebase without messing it up. Double-checked with [comparison](https://github.com/metabrainz/musicbrainz-server/compare/5197844a2b212bccd5475ee94d2041b8749dd270..ddeb294ee80dff1e7e7191b19617e46627478be0).

**Pull request merged**
