### PR TITLE
MBS-6530: Remove Google Analytics

### PR DESCRIPTION
**Pull request by chirlu**

### CODE REVIEW

**Comment by mwiencek** [comment]
I'm in favor but I think we should have another solution in place for getting browser stats first.

**Comment by uklauer** [comment]
I’m not sure we have that much of a choice. Let’s see what @mayhem has to say about it, since he will be the one to pay the fine. ;-)

**Comment by uklauer** [comment]
Discussion at https://chatlogs.metabrainz.org/brainzbot/metabrainz/2016-11-22/?msg=3744550&page=1

**Comment by yvanzo** [comment]
I rebased this PR with current `master` branch, and removed GA code that has been moved to React.

**Pull request merged**
