### PR TITLE
MBS-11991: Add links for uses of artist credits in entity editor

### PR DESCRIPTION
**Pull request by reosarevok**
### Implement MBS-11991

Tested manually.

This is now used in exactly the same way in two places (here and in ArtistCreditList). We could turn it into its own component but I'm not sure if it makes sense yet. Let me know what you think! :)

### CODE REVIEW

**Comment by reosarevok** [comment]
@brainzbot, retest this please

**Comment by yvanzo** [comment]
@brainzbot, retest this please

**Comment by yvanzo** [comment]
@reosarevok Can you please attach screenshots to this ticket to help with finding the changes? Its description is pretty vague.

**Comment by reosarevok** [comment]
Sure. It adds the "see uses" links to the artist edit page:

Screenshot from 2021-11-22 19-07-06

**Review by yvanzo — APPROVED** [review]
Thank you, I attached a modified version of it to the ticket.

**Pull request merged**
