### PR TITLE
MBS-10160: Display username on sidebar for youtube/c/ links

### PR DESCRIPTION
**Pull request by reosarevok**
https://tickets.metabrainz.org/browse/MBS-10160

It's unclear to me ATM if we should just clean those up to remove /c/ (the one case I tried worked without it), but this shouldn't hurt in the meantime.

### CODE REVIEW

**Comment by reosarevok** [comment]
My point is https://www.youtube.com/MetaBrainz is the same as https://www.youtube.com/c/MetaBrainz :)

**Comment by yvanzo** [comment]
Oh, we should probably keep only one format then. I would be surprised if there is no doc about this.

**Comment by reosarevok** [comment]
https://support.google.com/youtube/answer/2657968?hl=en "This is called a custom URL and looks like youtube.com/yourcustomname and youtube.com/c/yourcustomname" - sounds like they are equivalent, yes.

**Comment by reosarevok** [comment]
@yvanzo: added a cleanup for removing /c/, let me know if it seems ok.

**Pull request merged**
