### PR TITLE
MBS-10307, MBS-10463, MBS-11677: CAA improvements

### PR DESCRIPTION
**Pull request by mwiencek**
MBS-10307: Cover art types selector are inconsistent between add and edit actions
MBS-10463: Remove the iframe-based cover art image uploader
MBS-11677: Add Selenium tests for the CAA

### CODE REVIEW

**Comment by mwiencek** [comment]
@brainzbot test this please

**Comment by mwiencek** [comment]
@brainzbot test this please

**Comment by mwiencek** [comment]
@brainzbot test this please

**Review by reosarevok — APPROVED** [review]
I looked through this and it seems sensible enough, but I only could actually test the look of the cover art editing checkboxes. I'd suggest to put this on beta and see what happens, assuming you've tested that the basic use cases edit the types correctly at least.

**Pull request merged**
