### PR TITLE
MBS-9947: Permit podcast episodes on Spotify and Deezer

### PR DESCRIPTION
**Pull request by dominikh**

### CODE REVIEW

**Comment by dominikh** [comment]
Examples:

https://open.spotify.com/episode/5yyMb4t3PWlikJNucu9A6Z and https://www.deezer.com/en/episode/3495945

**Comment by yvanzo** [comment]
Hi,

Thank you for this patch. Please add related tests to [root/static/scripts/tests/Control/URLCleanup.js](https://github.com/metabrainz/musicbrainz-server/blob/master/root/static/scripts/tests/Control/URLCleanup.js)

I created the corresponding ticket as [MBS-9947](https://tickets.metabrainz.org/browse/MBS-9947) and renamed the PR accordingly.

Cheers

**Comment by dominikh** [comment]
PTAL

**Comment by yvanzo** [comment]
@brainzbot test this please.

**Pull request merged**
